server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:postgresql://192.168.1.117:5432/employeedb 
    username: appadmin
    password: password123

  profiles:
    active: "@profileActive@"
  main:
    banner-mode: "off"

logging:
  level:
    .: error
    org.springframework: ERROR


dbase_table: employee_table
environment: base
