server:
  port: 8081

spring:
  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:postgresql://192.168.1.117:5432/employeedb_dev
    username: appadmin
    password: password123

  profiles: dev

dbase_table: employee_table
environment: development
